esphome:
  name: meanwell-npb-can
  friendly_name: MeanWell NPB CAN
  name_add_mac_suffix: false

esp32:
  board: heltec_wifi_lora_32_V3
  framework:
    type: esp-idf

logger:

ota:
  - platform: esphome

# Wi-Fi вводится через Captive Portal (пароль к домашнему Wi-Fi не вшивается)
wifi:
  ap:
    ssid: "NPB-CAN-Setup"
    password: "12345678"

# Enable Home Assistant API
api:

web_server:
  port: 80
  version: 3
  sorting_groups:
     - id: grp_sensor
       name: "sensor"
       sorting_weight: 1
     - id: grp_set_cr
       name: "Управление зарядом"
       sorting_weight: 2
     - id: grp_set_bp
       name: "Управление БП"
       sorting_weight: 3
     - id: grp_err
       name: "Ошибки"
       sorting_weight: 4

# copy all of the contents below this line into your own esphome device ----------------

# general design
# this code simply exposes the meanwell npb 750 and its up to the automation in home assistant to control it correctly and safely


# these numbers are exposed to home assistant to allow them to be set through the ui or in your automation
# voltage and current can be controlled and you have to make sure that you stay within the ranges supported by your battery
# they are optimistic so they will be set and then the sensor values for the accepted target values will be updated to show that they took effect 
number:
  - platform: template
    name: meanwell next target current
    id: meanwell_next_target_current
    optimistic: true
    set_action:
      - canbus.send:
              use_extended_id: true
              can_id: 0xC0103
              data: !lambda return {0x30, 0x00, static_cast<uint8_t>( (int) (x * 100.0) % 256), static_cast<uint8_t>( x * 100.0 / 256.0 )};
    unit_of_measurement: "A"
    min_value: 0
    max_value: 1000
    step: 0.1
  - platform: template
    name: meanwell next target voltage
    id: meanwell_next_target_voltage
    optimistic: true
    set_action:
      - canbus.send:
              use_extended_id: true
              can_id: 0xC0103
              data: !lambda return {0x20, 0x00, static_cast<uint8_t>( (int) (x * 100.0) % 256), static_cast<uint8_t>( x * 100.0 / 256.0 )};
    unit_of_measurement: "V"
    min_value: 25   # could go to 21V but what is the point - we only want to charge
    max_value: 28.8 # could go to 41V but we dont want to damage the 24 lifepo4 battery
    step: 0.1

# this button if pressed in home assitant initializes the meanwell to become a power supply
# this usually has to be done only once and then the power supply should be turned off and on to accept the setting
# if in doubt check the flags if eeprom writing is off and if the mode is power supply or not
# the device will not be in "ready" state until these settings have been made
button:
  - platform: template
    name: initialize meanwell button
    id: initialize_meanwell_button
    on_press:
      - logger.log: Button Pressed
      - canbus.send:
          use_extended_id: true
          can_id: 0xC0103
          data: [0xB4, 0x00, 0x04 ,0x00] # this switches to power supply mode, turn off and on is required to make this real
      - delay: 100ms                      # write commands will not yield a response
      - canbus.send:
          use_extended_id: true
          can_id: 0xC0103
          data: [0xC2, 0x00, 0x03, 0x04] # this turns the eeprom writing off, turn off and on is required to make this real
      - delay: 100ms  

# this switch allows to turn the meanwell on
# only turn it on if it is in "ready" state
switch:    
  - platform: template
    name: power meanwell button
    id: power_meanwell_button
    turn_on_action:
      - canbus.send:
          use_extended_id: true
          can_id: 0xC0103
          data: [0x00, 0x00, 0x01] # turns meanwell on
    turn_off_action:
      - canbus.send:
          use_extended_id: true
          can_id: 0xC0103
          data: [0x00, 0x00, 0x00] # turns meanwell off

# this state aggregates all flags needed into one flag so your home assistant logic knows if this thing is ready or not
binary_sensor:
  - platform: template
    name: over temperature
    id: mw_over_temperature
  - platform: template
    name:  output over voltage
    id: mw_output_over_voltage
  - platform: template
    name:  output over current
    id: mw_output_over_current
  - platform: template
    name:  output short circuited
    id: mw_output_short_circuited
  - platform: template
    name:  AC abnormal
    id: mw_ac_abnormal
  - platform: template
    name:  output turned off
    id: mw_output_turned_off
  - platform: template
    name:  internal temperature abnormal
    id: mw_internal_temperature_abnormal
  - platform: template
    name:  temperature compensation short circuited
    id: mw_temperature_compensation_short_circuited
  - platform: template
    name:  no battery detected
    id: mw_no_battery_detected
  - platform: template
    name:  fully charged
    id: mw_fully_charged
  - platform: template
    name:  wake up unfinished
    id: mw_wake_up_unfinished
  - platform: template
    name:  DC output normal range
    id: mw_dc_output_normal_range
  - platform: template
    name:  initial state
    id: mw_initial_state
  - platform: template
    name:  eeprom access error
    id: mw_eeprom_access_error
  - platform: template
    name:  charger mode
    id: mw_charger_mode
  - platform: template
    name:  disable write to eeprom
    id: mw_disable_write_to_eeprom

# these are the sensors for actual and target current and voltage
sensor:
  - platform: template
    name: meanwell measured current
    id: meanwell_measured_current
    unit_of_measurement: "A"
    device_class: "current"
    state_class: "measurement"
    accuracy_decimals: 2
  - platform: template
    name: meanwell target current
    id: meanwell_target_current
    unit_of_measurement: "A"
    device_class: "current"
    state_class: "measurement"
    accuracy_decimals: 2
  - platform: template
    name: meanwell measured voltage
    id: meanwell_measured_voltage
    unit_of_measurement: "V"
    device_class: "voltage"
    state_class: "measurement"
    accuracy_decimals: 2
  - platform: template
    name: meanwell target voltage
    id: meanwell_target_voltage
    unit_of_measurement: "V"
    device_class: "voltage"
    state_class: "measurement"
    accuracy_decimals: 2
  - platform: template
    name: meanwell temperature
    id: meanwell_temperature
    unit_of_measurement: "°"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 2

# this is the defintion of the canbus interface for the esp32
canbus:
  - platform: esp32_can
    tx_pin: GPIO04
    rx_pin: GPIO05
    can_id: 0xc0003
    use_extended_id: true
    bit_rate: 250kbps
    on_frame:
    - can_id: 0xC0003
      use_extended_id: true
      then:
      - lambda: |-
          switch(x[0]) { 
            case 0x00:  ESP_LOGD("OPERATION         01 0x0000", "%02x", x[2]); 
                        id(power_meanwell_button).publish_state(x[2]);
                        break;
            case 0x20:  ESP_LOGD("VOUT_SET             0x0020", "%f V", 0.01 * ((float) x[2] + 256.0 * (float) x[3]));
                        id(meanwell_target_voltage).publish_state(    0.01 * ((float) x[2] + 256.0 * (float) x[3]));
                        break;
            case 0x30:  ESP_LOGD("IOUT_SET             0x0030", "%f A", 0.01 * ((float) x[2] + 256.0 * (float) x[3]));
                        id(meanwell_target_current).publish_state(    0.01 * ((float) x[2] + 256.0 * (float) x[3]));
                        break;
            case 0x40:  ESP_LOGD("FAULT_STATUS      00 0x0040", "%02x", x[2]);
                        id(mw_over_temperature                          ).publish_state((x[2] & 0x02) != 0);               // has to be 0
                        id(mw_output_over_voltage                       ).publish_state((x[2] & 0x04) != 0);               // has to be 0
                        id(mw_output_over_current                       ).publish_state((x[2] & 0x08) != 0);               // has to be 0
                        id(mw_output_short_circuited                    ).publish_state((x[2] & 0x10) != 0);               // has to be 0
                        id(mw_ac_abnormal                               ).publish_state((x[2] & 0x20) != 0);               // has to be 0
                        id(mw_output_turned_off                         ).publish_state((x[2] & 0x40) != 0);
                        id(mw_internal_temperature_abnormal             ).publish_state((x[2] & 0x80) != 0);               // has to be 0
                        break;
            case 0x60:  ESP_LOGD("READ_VOUT            0x0060", "%f V", 0.01 * ((float) x[2] + 256.0 * (float) x[3]));
                        id(meanwell_measured_voltage).publish_state(    0.01 * ((float) x[2] + 256.0 * (float) x[3]));
                        break;
            case 0x61:  ESP_LOGD("READ_IOUT            0x0061", "%f A", 0.01 * ((float) x[2] + 256.0 * (float) x[3]));
                        id(meanwell_measured_current).publish_state(    0.01 * ((float) x[2] + 256.0 * (float) x[3]));
                        break;
            case 0x62:  ESP_LOGD("READ_TEMPERATURE_1   0x0062", "%f °", 0.1  * ((float) x[2] + 256.0 * (float) x[3]));
                        id(meanwell_temperature).publish_state(         0.1 * ((float) x[2] + 256.0 * (float) x[3]));
                        break;
            case 0xB4:  ESP_LOGD("CURVE_CONFIG low  04 0x00B4", "%02x", x[2]);
                        ESP_LOGD("CURVE_CONFIG high 00 0x00B4", "%02x", x[3]);
                        id(mw_charger_mode                              ).publish_state((x[2] & 0x80) != 0);       // has to be 0 to allow control of current and voltage
                        break;
            case 0xB8:  ESP_LOGD("CHG_STATUS low    00 0x00B8", "%02x", x[2]);
                        ESP_LOGD("CHG_STATUS high   00 0x00B8", "%02x", x[3]);
                        id(mw_fully_charged                             ).publish_state((x[2] & 0x01) != 0);
                        id(mw_wake_up_unfinished                        ).publish_state((x[2] & 0x20) != 0);
                        id(mw_temperature_compensation_short_circuited  ).publish_state((x[3] & 0x04) != 0);     // has to be 0
                        id(mw_no_battery_detected                       ).publish_state((x[3] & 0x08) != 0);     // has to be 0, without battery no normal operation
                        break;
            case 0xC1:  ESP_LOGD("SYSTEM_STATUS     02 0x00C1", "%02x", x[2]);
                        id(mw_dc_output_normal_range                    ).publish_state((x[2] & 0x02) != 0);     // has to be 1, should be in normal range
                        id(mw_initial_state                             ).publish_state((x[2] & 0x20) != 0);
                        id(mw_eeprom_access_error                       ).publish_state((x[2] & 0x40) != 0);     // has to be 0, if eeprom is broken meanwell stops working
                        break;
            case 0xC2:  ESP_LOGD("SYSTEM_CONFIG low 03 0x00C2", "%02x", x[2]);
                        ESP_LOGD("SYSTEM_CONFIG high04 0x00C2", "%02x", x[3]);
                        id(mw_disable_write_to_eeprom                   ).publish_state((x[3] & 0x04) != 0);     // has to be 1, needed to protect eeprom
                        break;
           }

# this triggers canbus to share once a second all values of all relevant registers 
time:
  - platform: sntp
    on_time:
      - seconds: /1
        then:
          - canbus.send:
              use_extended_id: true
              can_id: 0xC0103
              data: [0x00, 0x00]
          - delay: 50ms # delay between sends minimum 30 ms to allow for receiving of the result to happen
          - canbus.send:
              use_extended_id: true
              can_id: 0xC0103
              data: [0x20, 0x00]
          - delay: 50ms
          - canbus.send:
              use_extended_id: true
              can_id: 0xC0103
              data: [0x30, 0x00]
          - delay: 50ms
          - canbus.send:
              use_extended_id: true
              can_id: 0xC0103
              data: [0x40, 0x00]
          - delay: 50ms
          - canbus.send:
              use_extended_id: true
              can_id: 0xC0103
              data: [0x60, 0x00]
          - delay: 50ms
          - canbus.send:
              use_extended_id: true
              can_id: 0xC0103
              data: [0x61, 0x00]
          - delay: 50ms
          - canbus.send:
              use_extended_id: true
              can_id: 0xC0103
              data: [0x62, 0x00]
          - delay: 50ms
          - canbus.send:
              use_extended_id: true
              can_id: 0xC0103
              data: [0xB4, 0x00]
          - delay: 50ms
          - canbus.send:
              use_extended_id: true
              can_id: 0xC0103
              data: [0xB8, 0x00]
          - delay: 50ms
          - canbus.send:
              use_extended_id: true
              can_id: 0xC0103
              data: [0xC1, 0x00]
          - delay: 50ms
          - canbus.send:
              use_extended_id: true
              can_id: 0xC0103
              data: [0xC2, 0x00] # we should be at 550ms which means half of the second has passed
